# action.yml
name: pasarif
author: yolocs
description: 'Installs pasarif and includes it in your path'
branding:
  icon: 'package'
  color: 'blue'
runs:
  using: "composite"
  steps:
    # We verify the version against a SHA **in the published action itself**, not in the GCS bucket.
    - shell: bash
      run: |
        #!/bin/bash
        echo "installing pasarif via 'go install' from its main version"
        go install github.com/yolocs/pasarif@main
        exit 0
    - if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      run:  echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      shell: bash
    - if: ${{ runner.os == 'Windows' }}
      run:  echo "$(go env GOPATH)/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh